name: Add Comment on Commit

on:
    workflow_run:
        workflows: 
            - Generate Image and Push to Github Pages
        types:
            - completed

permissions:
    contents: write
    actions: read

jobs:
    add-comment-on-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Download generated image artifact
              uses: actions/download-artifact@v4
              with:
                name: generated-image
                path: ./artifacts
                github-token: ${{ secrets.GITHUB_TOKEN }}
                run-id: ${{ github.event.workflow_run.id }}

            - name: Get Image URL from artifact
              run: |
                echo "IMAGE_NAME=$(ls ./artifacts | head -n 1)" >> $GITHUB_ENV

            - name: Build Image URL
              run: |
                echo "IMAGE_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/images/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

            - name: Add Comment on Commit
              uses: actions/github-script@v6
              with:
                script: |
                    await github.rest.repos.createCommitComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        commit_sha: context.payload.workflow_run.head_sha,
                        body: `Nouveau commit sur la branche main : **${{ env.COMMIT_MESSAGE }}**\n\n![Generated Image](${{ env.IMAGE_URL }})`
                    })
