name: Generate Image and Push to Github Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-image:
        runs-on: ubuntu-latest
        steps:
            - name: Clone GitHub Repo
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 26

            - name: Get last commit message
              run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
            
            - name: Generate Image using Curl
              run: |
                RESPONSE=$(curl -d '{
                        "format": "jpeg",
                        "metadata": "some text",
                        "params": [
                            {
                            "name": "text2",
                            "imageUrl": "Message de commit:"
                            },
                            {
                            "name": "text3",
                            "text": "${{ env.COMMIT_MESSAGE }}"
                            }
                        ]
                        }' \
                -H "Authorization: Bearer ${{ secrets.API_UID }}" \
                -H "Content-Type: application/json" \
                -X POST https://api.dynapictures.com/designs/e789eaf793)

                echo "Réponse API :"
                echo "$RESPONSE"

            - name: Get Image URL
              run: |
                IMAGE_URL=$(jq -r '.imageUrl' response.json)
                echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
                echo "Image URL: $IMAGE_URL"

            - name: Save Image in images folder
              run: |
                mkdir -p public/images
                curl -L -o public/images/img-${{ github.sha }}.jpeg ${{ env.IMAGE_URL }}

            - name: Generate index.html for GitHub Pages
              run: node ./scripts/generate-html-index.js

            - name: Commit and Push Changes
              run: |
                git config --global user.name "OtterBot"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add public/
                git commit -m "Add generated image and update index.html for commit ${{ github.sha }}"
                git push

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public